version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  datastore:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  write:
    build: ./write-service
    ports:
      - 8081:8080
    volumes:
      - ./write-service/build/libs/:/app
    links:
      - kafka
      - zookeeper
      - datastore
    environment:
      SPRING_JPA_DATABASE: MYSQL
      SPRING_DATABSOURCE_PLATFORM: mysql
  #    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/writedb?setAutoCommit=true&useSSL=false&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_URL: jdbc:mysql://datastore:3306/writedb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      KAFKA_TOPIC_NAME: cqrs

  read:
    build: ./read-service
    ports:
      - 8082:8080
    volumes:
      - ./read-service/build/libs/:/app
    links:
      - kafka
      - zookeeper
      - datastore
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://datastore:3306/readdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      KAFKA_TOPIC_NAME: cqrs
